import {
  GenderEnum,
  NationalityEnum,
  ReligionEnum,
  ScientificDivisionEnum,
} from "@fcai-sis/shared-models";

export const dummyStudents = [
  {
    address: "٢٢ شارع عامر، الدقي، الجيزة",
    administration: "الدقي",
    birthDay: 12,
    birthMonth: 12,
    birthPlace: "Cairo",
    birthYear: 1999,
    directorate: "الجيزة",
    educationType: "ثانوي",
    fullName: "يوسف جلال الدين ناظم حيدر الطائي",
    gender: GenderEnum[0],
    governorateId: 21,
    nationalId: "20304162100315",
    nationality: NationalityEnum[0],
    phoneNumber: "01241352622",
    religion: ReligionEnum[0],
    scientificDivision: ScientificDivisionEnum[1],
    studentId: "20200645",
    currentGpa: 3.5,
    currentLevel: 1,
  },
  {
    address: "٣٣ جابر بن حيان الدقي، الجيزة",
    administration: "الدقي",
    birthDay: 3,
    birthMonth: 2,
    birthPlace: "Cairo",
    birthYear: 2000,
    directorate: "الجيزة",
    educationType: "ثانوي",
    fullName: "محمد علي الحسيني",
    gender: GenderEnum[0],
    governorateId: 21,
    nationalId: "20004162100315",
    nationality: NationalityEnum[0],
    phoneNumber: "01241352622",
    religion: ReligionEnum[0],
    scientificDivision: ScientificDivisionEnum[1],
    studentId: "20200123",
    currentGpa: 2.21,
    currentLevel: 3,
  },
] as const;
